title: "Data Science Analyst Portfolio"
description: "Welcome to my portfolio! I am a data analyst dedicated to transforming complex data into actionable insights, showcasing my expertise in SQL, Python, and Data Visualization to drive impactful, data-informed decisions."
theme: minima
baseurl: "" # Leave this empty for GitHub Pages
url: "https://nadaysdn.github.io" # Replace with your GitHub Pages URL

# Navigation Links
nav_links:
  - title: "Skills"
    url: "/skills/"
  - title: "Projects"
    url: "/projects/"
  - title: "Experiences"
    url: "/experiences/"
  - title: "Education"
    url: "/education/"
  - title: "Contact"
    url: "/contact/"

  <footer>
    <p><strong>Author:</strong> Nada Asri</p>
    <p><strong>Email:</strong> <a href="mailto:nadaasriyasdana@gmail.com">nadaasriyasdana@gmail.com</a></p>
    <p><strong>Phone:</strong> <a href="https://wa.me/081223857175">+62 812 2385 7175</a></p>
    <p>
      <strong>Social Links:</strong>
      <a href="https://github.com/nadaysdn" target="_blank">GitHub</a> |
      <a href="https://linkedin.com/in/nadaysdn" target="_blank">LinkedIn</a>
    </p>
    <p>&copy; {{ site.time | date: '%Y' }} Nada Asri. All rights reserved.</p>
  </footer>
